wallpaper {
	monitor = DP-1
	path = ~/nixos/wallpapers/Guts_01.jpg
	fit_mode = cover
}

wallpaper {
	monitor = DP-2
	path = ~/nixos/wallpapers/Eva_Girls.jpeg
	fit_mode = cover
}

wallpaper {
	monitor = HDMI-A-1
	path = ~/nixos/wallpapers/Eva_01.jpg
	fit_mode = cover
}

splash = false
ipc = off
