preload = ~/nixos/wallpapers/Guts_01.jpg
preload = ~/nixos/wallpapers/Eva_01.jpg
preload = ~/nixos/wallpapers/Eva_Girls.jpeg
wallpaper = DP-1, ~/nixos/wallpapers/Guts_01.jpg
wallpaper = DP-2, ~/nixos/wallpapers/Eva_Girls.jpeg
wallpaper = HDMI-A-1, ~/nixos/wallpapers/Eva_01.jpg
